services:
  mariadb:
    image: 'mariadb:latest'
    container_name: CrediYa_db
    restart: unless-stopped
    environment:
      COMPOSE_PROJECT_NAME: "Auth"
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "zaA41.Vv8_q96/Y>"
      MYSQL_DATABASE: "auth"
      MYSQL_USER: "CrediUserdata"
      MYSQL_PASSWORD: "za.8%q96@Y>"
    ports:
      - "3306:3306" # Map host port 3306 to container port 3306
    volumes:
      - mariadb_data:/var/lib/mysql # Persist data to a Docker volume
      - ./init-scripts:/docker-entrypoint-initdb.d # Optional: for initial SQL scripts
  auth:
    image: auth
    build:
      context: ./Deployment
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      serviceName: mariadb
 # sonarqube:
 #   image: sonarqube:community
 #   ports:
 #     - "9000:9000"
 #   environment:
 #     - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
 #     - SONARQUBE_JDBC_USERNAME=sonar
 #     - SONARQUBE_JDBC_PASSWORD=sonar
 #   volumes:
 #     - sonarqube_data:/opt/sonarqube/data
 #     - sonarqube_extensions:/opt/sonarqube/extensions
 #     - sonarqube_logs:/opt/sonarqube/logs
 #   depends_on:
 #     - db
volumes:
 # sonarqube_data:
 # sonarqube_extensions:
 # sonarqube_logs:
  mariadb_data:
