services:
  mariadb:
    image: 'mariadb:latest'
    container_name: CrediYa_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "zaA41\"Vv8%q96@Y>"
      MYSQL_DATABASE: "auth"
      MYSQL_USER: "CrediUserdata"
      MYSQL_PASSWORD: "za.8%q96@Y>"
    ports:
      - "3306:3306" # Map host port 3306 to container port 3306
    volumes:
      - mariadb_data:/var/lib/mysql # Persist data to a Docker volume
      - ./init-scripts:/docker-entrypoint-initdb.d # Optional: for initial SQL scripts
volumes:
  mariadb_data:
