server:
  port: 8080
  data:
    r2dbc:
      repositories:
        enabled: true
spring:
  r2dbc:
    url: "r2dbc:mariadb//localhost:3306"
    host: "host.docker.internal"
    port: "3306"
    database: "auth"
    username: "CrediUserdata"
    password: "za.8%q96@Y>"
  application:
    name: "CrediYa.Autenticacion"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080,http://localhost:8081"
loggin:
  level:
    org.springframework.r2dbc=DEBUG:
jwt:
  secret: "MWphLWQhaDNpX2RycWh8Zjl6N0BzYjRyOHfDsWx5Lzk3eGZ2LnY1"   #${JWT_SECRET}
  expiration: 3600000 #${JWT_EXPIRATION}
  expirationRefresh: 300000   #${JWT_EXPIRATION_REFRESH}
