services:
  mariadb:
    image: 'mariadb:latest'
    container_name: CrediYa_db
    restart: unless-stopped
    environment:
      COMPOSE_PROJECT_NAME: "Auth"
      MYSQL_ROOT_PASSWORD: "zaA41.Vv8_q96/Y>"
      MYSQL_DATABASE: "auth"
      MYSQL_USER: "CrediUserdata"
      MYSQL_PASSWORD: "za.8%q96@Y>"
    ports:
      - "3306:3306" # Map host port 3306 to container port 3306
    volumes:
      - mariadb_data:/var/lib/mysql/auth/ # Persist data to a Docker volume
      - ./init-scripts/auth:/docker-entrypoint-initdb.d # Optional: for initial SQL scripts

  dbloan:
    image: 'mariadb:latest'
    container_name: CrediYa_loan_db
    restart: unless-stopped
    environment:
      COMPOSE_PROJECT_NAME: "Loan"
      MYSQL_ROOT_PASSWORD: "zaA41.Vv8_q96/Y>"
      MYSQL_DATABASE:  "application"
      MYSQL_USER: "CrediUserdata"
      MYSQL_PASSWORD: "za.8_q96@Y>"
    ports:
      - "3316:3306" # Map host port 3316 to container port 336
    volumes:
      - loandb_data:/var/lib/mysql/loan/ # Persist data to a Docker volume
      - ./init-scripts/loan:/docker-entrypoint-initdb.d # Optional: for initial SQL scripts

  auth:
    image: auth
    build:
      context: ./MicroservicioAutenticacion
      dockerfile: Deployment/Dockerfile
    container_name: Auth-Services
    ports:
      - 8080:8080
    depends_on:
      - mariadb
    networks:
      - crediYa-network

  loan:
    image: loan
    build:
      context: ./MicroservicioSolicitudes
      dockerfile: Deployment/Dockerfile
    container_name: Loan-Services
    ports:
      - 8081:8081
    depends_on:
      - dbloan
      - auth
    networks:
      - crediYa-network

volumes:
  mariadb_data:
  loandb_data:

networks:
  crediYa-network:
    driver: bridge